In [5]:
import pandas as pd

df = pd.read_spss("fashion.sav")
df

        id            Q1                     Q2     Q3   AGE   GENDER  INCOME
0    170.0   Очень важна       Раз в 1-3 месяца   30.0  16.0  женский   460.0
1     99.0   Очень важна       Раз в 1-3 месяца   30.0  17.0  женский   450.0
2    130.0   Очень важна  Несколько раз в месяц   30.0  17.0  женский   470.0
3    177.0   Очень важна  Несколько раз в месяц   30.0  17.0  женский   550.0
4     18.0   Очень важна  Несколько раз в месяц   30.0  18.0  женский   420.0
..     ...           ...                    ...    ...   ...      ...     ...
195    4.0  Скорее важна       Раз в 1-3 месяца  400.0  31.0  женский  1850.0
196  190.0  Скорее важна       Раз в 1-3 месяца  400.0  32.0  женский  1500.0
197   14.0  Скорее важна       Раз в 1-3 месяца  400.0  32.0  женский  1700.0
198   43.0  Скорее важна       Раз в 1-3 месяца  420.0  33.0  мужской  1900.0
199   22.0  Скорее важна       Раз в 1-3 месяца  420.0  34.0  женский  1800.0

[200 rows x 7 columns]

In [6]:
df.describe()

               id          Q3         AGE       INCOME
count  200.000000  200.000000  200.000000   200.000000
mean   100.500000  151.275000   22.620000   960.425000
std     57.879185  118.223872    4.829308   477.452878
min      1.000000   30.000000   16.000000   380.000000
25%     50.750000   65.000000   19.000000   695.000000
50%    100.500000   90.000000   22.000000   760.000000
75%    150.250000  220.000000   25.000000  1200.000000
max    200.000000  420.000000   35.000000  2950.000000

In [10]:
pd.unique(df.values.ravel())

array([170.0, 'Очень важна', 'Раз в 1-3 месяца', 30.0, 16.0, 'женский',
       460.0, 99.0, 17.0, 450.0, 130.0, 'Несколько раз в месяц', 470.0,
       177.0, 550.0, 18.0, 420.0, 147.0, 'Скорее важна', 19.0, 186.0,
       22.0, 400.0, 'Скорее не важна', 23.0, 'мужской', 68.0, 40.0, 435.0,
       104.0, 'Раз в полгода-год', 440.0, 108.0, 82.0, 24.0, 430.0, 64.0,
       175.0, 380.0, 200.0, 32.0, 35.0, 800.0, 77.0, 650.0, 94.0,
       'Несколько раз в неделю и чаще', 660.0, 112.0, 670.0, 187.0, 700.0,
       36.0, 500.0, 138.0, 148.0, 680.0, 109.0, 42.0, 75.0,
       'Раз в год и реже', 26.0, 34.0, 'Совсем не важна', 27.0, 900.0,
       189.0, 50.0, 84.0, 25.0, 121.0, 600.0, 152.0, 72.0, 28.0, 720.0,
       162.0, 730.0, 830.0, 171.0, 870.0, 110.0, 90.0, 52.0, 179.0, 60.0,
       53.0, 198.0, 59.0, 114.0, 47.0, 178.0, 164.0, 65.0, 165.0, 119.0,
       31.0, 61.0, 33.0, 54.0, 70.0, 81.0, 78.0, 97.0, 131.0, 193.0,
       163.0, 63.0, 21.0, 58.0, 155.0, 69.0, 153.0, 89.0, 120.0, 37.0,
       950.0, 15.0, 129.0, 154.0, 167.0, 740.0, 143.0, 133.0, 80.0, 185.0,
       6.0, 48.0, 20.0, 91.0, 92.0, 88.0, 102.0, 145.0, 182.0, 73.0, 74.0,
       820.0, 142.0, 55.0, 66.0, 760.0, 57.0, 1260.0, 132.0, 176.0, 86.0,
       195.0, 8.0, 38.0, 71.0, 106.0, 197.0, 41.0, 100.0, 160.0, 780.0,
       10.0, 125.0, 156.0, 181.0, 144.0, 980.0, 140.0, 1250.0, 5.0, 150.0,
       67.0, 166.0, 95.0, 1000.0, 115.0, 1200.0, 13.0, 1380.0, 134.0,
       85.0, 124.0, 79.0, 126.0, 7.0, 1780.0, 127.0, 173.0, 1300.0, 196.0,
       2300.0, 3.0, 139.0, 29.0, 49.0, 1100.0, 141.0, 76.0, 194.0, 111.0,
       149.0, 184.0, 168.0, 1.0, 12.0, 169.0, 93.0, 1700.0, 98.0, 56.0,
       1500.0, 117.0, 220.0, 161.0, 1450.0, 191.0, 480.0, 137.0, 1800.0,
       158.0, 159.0, 101.0, 199.0, 9.0, 2.0, 39.0, 1900.0, 62.0, 192.0,
       151.0, 300.0, 2100.0, 45.0, 2000.0, 172.0, 157.0, 122.0, 1600.0,
       340.0, 116.0, 46.0, 87.0, 128.0, 188.0, 180.0, 96.0, 44.0, 350.0,
       2950.0, 136.0, 1350.0, 123.0, 360.0, 83.0, 2200.0, 118.0, 135.0,
       103.0, 51.0, 1400.0, 11.0, 105.0, 146.0, 174.0, 113.0, 107.0,
       2500.0, 183.0, 4.0, 1850.0, 190.0, 14.0, 43.0], dtype=object)

In [ ]:
df = pd.read_spss()
df

,id,instrument,a1,a2,a3,a4,a5,a6,a7,a8,...,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20
0,1.0,Скрипка,4.0,6.0,7.0,6.0,2.0,Полностью НЕ согласен,6.0,5.0,...,Не слушаю,Не слушаю,Не слушаю,Слушаю,Слушаю,Слушаю,Не слушаю,Слушаю,Не слушаю,Слушаю
1,2.0,Фортепиано,Полностью НЕ согласен,7.0,5.0,4.0,5.0,3.0,7.0,5.0,...,Слушаю,Слушаю,Не слушаю,Слушаю,Слушаю,Не слушаю,Слушаю,Слушаю,Слушаю,Не слушаю
2,3.0,Фортепиано,7.0,2.0,3.0,4.0,2.0,6.0,7.0,3.0,...,Не слушаю,Слушаю,Слушаю,Слушаю,Слушаю,Не слушаю,Не слушаю,Не слушаю,Слушаю,Слушаю
3,4.0,Фортепиано,2.0,2.0,6.0,2.0,6.0,7.0,7.0,6.0,...,Не слушаю,Не слушаю,Не слушаю,Не слушаю,Слушаю,Слушаю,Не слушаю,Слушаю,Слушаю,Слушаю
4,5.0,Гармонь/аккордеон,4.0,Полностью НЕ согласен,3.0,4.0,5.0,Полностью НЕ согласен,3.0,5.0,...,Не слушаю,Слушаю,Не слушаю,Слушаю,Не слушаю,Не слушаю,Не слушаю,Не слушаю,Слушаю,Слушаю
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296.0,Гитара,6.0,Полностью НЕ согласен,3.0,5.0,5.0,Полностью НЕ согласен,2.0,Полностью НЕ согласен,...,Не слушаю,Не слушаю,Слушаю,Слушаю,Слушаю,Слушаю,Не слушаю,Не слушаю,Слушаю,Не слушаю
296,297.0,Скрипка,6.0,6.0,2.0,5.0,6.0,7.0,3.0,6.0,...,Слушаю,Не слушаю,Не слушаю,Не слушаю,Слушаю,Слушаю,Слушаю,Не слушаю,Слушаю,Не слушаю
297,298.0,Гитара,6.0,5.0,2.0,6.0,7.0,2.0,4.0,6.0,...,Не слушаю,Слушаю,Не слушаю,Слушаю,Слушаю,Слушаю,Слушаю,Слушаю,Не слушаю,Не слушаю
298,299.0,Фортепиано,7.0,Полностью НЕ согласен,4.0,5.0,3.0,Полностью НЕ согласен,7.0,5.0,...,Не слушаю,Не слушаю,Слушаю,Слушаю,Слушаю,Не слушаю,Не слушаю,Слушаю,Слушаю,Слушаю
299,300.0,Фортепиано,7.0,Полностью НЕ согласен,3.0,6.0,7.0,Полностью НЕ согласен,5.0,7.0,...,Не слушаю,Слушаю,Не слушаю,Слушаю,Слушаю,Не слушаю,Не слушаю,Слушаю,Не слушаю,Слушаю

In [12]:
df.describe()

               id         AGE
count  300.000000  300.000000
mean   150.500000   25.866667
std     86.746758    4.787339
min      1.000000   18.000000
25%     75.750000   22.000000
50%    150.500000   26.000000
75%    225.250000   30.000000
max    300.000000   34.000000